### PR TITLE
Fix a small Waker bug

### PR DESCRIPTION
**Pull request by jeff-hiner**
Without this, a waker might be forgotten.

### CODE REVIEW

**Comment by xgroleau** [comment]
Hey sorry about that, I've never received the notification. Are those changes still relevant?
Also, I'm not sure if using a struct that is internal to the `future_core` crate is the way to go.

**Comment by xgroleau** [comment]
Actually while fixing the UB from miri, I needed to migrate to an AtomicWaker anyway.

**Comment by jeff-hiner** [comment]
Yeah, `tokio` essentially vendors in the `AtomicWaker` from `futures-core` by copying the code directly in. If you don't want to pull in a dependency you can do the same. In either case, trying to write your own is unnecessary (and very difficult to do correctly, as you've noticed!)

**Comment by xgroleau** [comment]
Fixed in the last commits btw with other issues, thanks for pointing it out!

**Pull request closed without merging**
